= Invalid execution results =
| ----------------- |
|     Thread 1      |
| ----------------- |
| operation(): void |
| ----------------- |

The following interleaving leads to the error:
| ----------- |
|  Thread 1   |
| ----------- |
| operation() |
| ----------- |

Detailed trace:
| ------------------------------------------------------------------------------------------------------------------------------------------ |
|                                                                  Thread 1                                                                  |
| ------------------------------------------------------------------------------------------------------------------------------------------ |
| operation()                                                                                                                                |
|   escape = "START" at InlineLambdaConditionalNotTakenThrowTest.<unknown method>(InlineLambdaConditionalNotTakenThrowTest.kt:32)            |
|   run() at InlineLambdaConditionalNotTakenThrowTest.<unknown method>(InlineLambdaConditionalNotTakenThrowTest.kt:34)                       |
|     setEscape("BEFORE BLOCK") at InlineLambdaConditionalNotTakenThrowTest.<unknown method>(InlineLambdaConditionalNotTakenThrowTest.kt:46) |
|       escape = "BEFORE BLOCK" at InlineLambdaConditionalNotTakenThrowTest.<unknown method>(InlineLambdaConditionalNotTakenThrowTest.kt:20) |
|     run$Lambda() at InlineLambdaConditionalNotTakenThrowTest.<unknown method>(InlineLambdaConditionalNotTakenThrowTest.kt:47)              |
|       escape = "IN LAMBDA" at InlineLambdaConditionalNotTakenThrowTest.<unknown method>(InlineLambdaConditionalNotTakenThrowTest.kt:35)    |
|       escape = "AFTER LAMBDA" at InlineLambdaConditionalNotTakenThrowTest.<unknown method>(InlineLambdaConditionalNotTakenThrowTest.kt:37) |
|     setEscape("AFTER BLOCK") at InlineLambdaConditionalNotTakenThrowTest.<unknown method>(InlineLambdaConditionalNotTakenThrowTest.kt:48)  |
|       escape = "AFTER BLOCK" at InlineLambdaConditionalNotTakenThrowTest.<unknown method>(InlineLambdaConditionalNotTakenThrowTest.kt:20)  |
|   escape = "END" at InlineLambdaConditionalNotTakenThrowTest.<unknown method>(InlineLambdaConditionalNotTakenThrowTest.kt:42)              |
|   result: void                                                                                                                             |
| ------------------------------------------------------------------------------------------------------------------------------------------ |
