= Invalid execution results =
Parallel part:
| operation(): 2 | operation(): 1 |

= The following interleaving leads to the error =
Parallel part trace:
|                      | operation()                                                                                                         |
|                      |   badMethod(): threw NotImplementedError at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:96) |
|                      |   counter.READ: 0 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:98)                        |
|                      |   counter.WRITE(1) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:98)                       |
|                      |   counter.READ: 1 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:99)                        |
|                      |   switch                                                                                                            |
| operation(): 2       |                                                                                                                     |
|   thread is finished |                                                                                                                     |
|                      |   counter.WRITE(2) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:99)                       |
|                      |   result: 1                                                                                                         |
|                      |   thread is finished                                                                                                |

Detailed parallel part trace:
|                                                                                                                     | operation()                                                                                                         |
|                                                                                                                     |   badMethod(): threw NotImplementedError at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:96) |
|                                                                                                                     |     useless.READ: 0 at CaughtExceptionMethodReportingTest.badMethod(MethodReportingTest.kt:104)                     |
|                                                                                                                     |     useless.WRITE(1) at CaughtExceptionMethodReportingTest.badMethod(MethodReportingTest.kt:104)                    |
|                                                                                                                     |   counter.READ: 0 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:98)                        |
|                                                                                                                     |   counter.WRITE(1) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:98)                       |
|                                                                                                                     |   counter.READ: 1 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:99)                        |
|                                                                                                                     |   switch                                                                                                            |
| operation()                                                                                                         |                                                                                                                     |
|   badMethod(): threw NotImplementedError at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:96) |                                                                                                                     |
|     useless.READ: 1 at CaughtExceptionMethodReportingTest.badMethod(MethodReportingTest.kt:104)                     |                                                                                                                     |
|     useless.WRITE(2) at CaughtExceptionMethodReportingTest.badMethod(MethodReportingTest.kt:104)                    |                                                                                                                     |
|   counter.READ: 1 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:98)                        |                                                                                                                     |
|   counter.WRITE(2) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:98)                       |                                                                                                                     |
|   counter.READ: 2 at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:99)                        |                                                                                                                     |
|   counter.WRITE(3) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:99)                       |                                                                                                                     |
|   result: 2                                                                                                         |                                                                                                                     |
|   thread is finished                                                                                                |                                                                                                                     |
|                                                                                                                     |   counter.WRITE(2) at CaughtExceptionMethodReportingTest.operation(MethodReportingTest.kt:99)                       |
|                                                                                                                     |   result: 1                                                                                                         |
|                                                                                                                     |   thread is finished                                                                                                |

= To reproduce exactly this test execution with the same scenarios, you can add this setting in your testing options configuration =
.withReproduceSettings("eyJyYW5kb21TZWVkR2VuZXJhdG9yU2VlZCI6LTUwMTkzMjIwNDM3NDUzMzc2NTl9")

= You can add this scenario as a custom test. Insert this code in your testing options configuration =
.addCustomScenario {
	parallel {
		thread {
			actor(::operation)
		}
		thread {
			actor(::operation)
		}
	}
}
