= Validation function validateWithError has failed =
| -------------------------------------------------------------- |
|                  Thread 1                  |     Thread 2      |
| -------------------------------------------------------------- |
| operation(): void                          |                   |
| -------------------------------------------------------------- |
| operation(): void                          | operation(): void |
| -------------------------------------------------------------- |
| operation(): void                          |                   |
| -------------------------------------------------------------- |
| validateWithError(): IllegalStateException |                   |
| -------------------------------------------------------------- |

---
All operations above the horizontal line | ----- | happen before those below the line
---


java.lang.IllegalStateException: Validation works!
	at org.jetbrains.kotlinx.lincheck_test.representation.ValidationFunctionCallTest.validateWithError(ValidationFunctionTests.kt:44)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution4.run(Unknown Source)
	at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.testThreadRunnable$lambda$10(FixedActiveThreadsExecutor.kt:172)
	at java.lang.Thread.run(Thread.java:750)


The following interleaving leads to the error:
| -------------------------------------------------------- |
|                  Thread 1                  |  Thread 2   |
| -------------------------------------------------------- |
| operation()                                |             |
| -------------------------------------------------------- |
|                                            | operation() |
| operation()                                |             |
| -------------------------------------------------------- |
| operation()                                |             |
| -------------------------------------------------------- |
| validateWithError(): IllegalStateException |             |
| -------------------------------------------------------- |

Detailed trace:
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|                                               Thread 1                                               |                                           Thread 2                                           |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| operation()                                                                                          |                                                                                              |
|   validateInvoked ⟶ 0 at ValidationFunctionCallTest.operation(ValidationFunctionTests.kt:36)         |                                                                                              |
|   result: void                                                                                       |                                                                                              |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|                                                                                                      | operation()                                                                                  |
|                                                                                                      |   validateInvoked ⟶ 0 at ValidationFunctionCallTest.operation(ValidationFunctionTests.kt:36) |
|                                                                                                      |   result: void                                                                               |
| operation()                                                                                          |                                                                                              |
|   validateInvoked ⟶ 0 at ValidationFunctionCallTest.operation(ValidationFunctionTests.kt:36)         |                                                                                              |
|   result: void                                                                                       |                                                                                              |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| operation()                                                                                          |                                                                                              |
|   validateInvoked ⟶ 0 at ValidationFunctionCallTest.operation(ValidationFunctionTests.kt:36)         |                                                                                              |
|   result: void                                                                                       |                                                                                              |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| validateWithError(): IllegalStateException                                                           |                                                                                              |
|   validateInvoked ⟶ 0 at ValidationFunctionCallTest.validateWithError(ValidationFunctionTests.kt:43) |                                                                                              |
|   validateInvoked = 1 at ValidationFunctionCallTest.validateWithError(ValidationFunctionTests.kt:43) |                                                                                              |
|   validateInvoked ⟶ 1 at ValidationFunctionCallTest.validateWithError(ValidationFunctionTests.kt:44) |                                                                                              |
|   result: IllegalStateException                                                                      |                                                                                              |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
